<template>
  <div class="report-preview-renderer">
    <!-- Report Cover -->
    <div class="preview-page cover-page">
      <div class="page-content">
        <div class="text-center">
          <!-- Company Logo -->
          <div v-if="hasSection('cover') && getSectionConfig('cover', 'include_logo')" class="company-logo mb-4">
            <img src="/images/logo-placeholder.png" alt="Company Logo" class="logo-img">
          </div>
          
          <!-- Report Title -->
          <h1 class="report-title mb-4">{{ settings.name || 'Financial Report' }}</h1>
          
          <!-- Client Information -->
          <div v-if="hasSection('cover') && getSectionConfig('cover', 'include_client_name')" class="client-info mb-4">
            <h3 class="client-name">{{ data.client?.first_name }} {{ data.client?.last_name }}</h3>
            <p class="client-subtitle text-muted">Retirement Planning Analysis</p>
          </div>
          
          <!-- Report Date -->
          <div v-if="hasSection('cover') && getSectionConfig('cover', 'include_date')" class="report-date">
            <p class="text-muted">{{ formatDate(new Date()) }}</p>
          </div>
          
          <!-- Template Style Badge -->
          <div class="template-badge mt-4">
            <span class="badge bg-primary fs-6">
              {{ getTemplateStyleLabel(getSectionConfig('cover', 'template_style', 'professional')) }} Report
            </span>
          </div>
        </div>
      </div>
    </div>

    <!-- Table of Contents -->
    <div v-if="hasSection('toc')" class="preview-page toc-page">
      <div class="page-content">
        <h2 class="page-title mb-4">Table of Contents</h2>
        <div class="toc-list">
          <div 
            v-for="(section, index) in visibleSections" 
            :key="section.uid"
            class="toc-item d-flex justify-content-between align-items-center"
          >
            <div class="d-flex align-items-center">
              <span class="section-number me-3">{{ index + 1 }}</span>
              <span class="section-title">{{ section.title }}</span>
            </div>
            <span class="page-number">{{ getEstimatedPageNumber(index) }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Report Sections -->
    <div 
      v-for="(section, index) in visibleSections" 
      :key="section.uid"
      class="preview-page content-page"
      :class="{ 'page-break-before': section.config.page_break_before }"
    >
      <div class="page-content">
        <!-- Section Header -->
        <div v-if="section.config.show_header !== false" class="page-header mb-4">
          <h2 class="page-title">{{ section.title }}</h2>
          <div v-if="section.description" class="page-subtitle text-muted">{{ section.description }}</div>
        </div>
        
        <!-- Section Content -->
        <div class="section-content">
          <SectionContentRenderer 
            :section="section" 
            :data="data"
            :settings="settings"
          />
        </div>
      </div>
    </div>

    <!-- Report Footer/Disclaimers -->
    <div class="preview-page footer-page">
      <div class="page-content">
        <div class="report-footer text-center">
          <div class="disclaimer mb-4">
            <h6>Important Disclaimers</h6>
            <p class="small text-muted">
              This report is for informational purposes only and does not constitute investment, legal, or tax advice. 
              Past performance does not guarantee future results. Please consult with qualified professionals 
              before making any financial decisions.
            </p>
          </div>
          
          <div class="contact-info">
            <p class="mb-1"><strong>Generated by RetirementAdvisorPro</strong></p>
            <p class="small text-muted">Professional Retirement Planning Software</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { computed } from 'vue'
import SectionContentRenderer from './SectionContentRenderer.vue'

export default {
  name: 'ReportPreviewRenderer',
  components: {
    SectionContentRenderer
  },
  props: {
    sections: {
      type: Array,
      required: true
    },
    data: {
      type: Object,
      default: () => ({})
    },
    settings: {
      type: Object,
      default: () => ({})
    }
  },
  setup(props) {
    // Filter out layout-only sections for content rendering
    const visibleSections = computed(() => {
      return props.sections.filter(section => 
        !['page_break', 'spacer', 'cover', 'toc'].includes(section.type)
      )
    })

    // Helper methods
    const hasSection = (sectionType) => {
      return props.sections.some(section => section.type === sectionType)
    }

    const getSectionConfig = (sectionType, configKey, defaultValue = null) => {
      const section = props.sections.find(s => s.type === sectionType)
      return section?.config?.[configKey] ?? defaultValue
    }

    const getEstimatedPageNumber = (index) => {
      // Base pages: cover (1) + toc (1 if exists)
      let pageNumber = 2
      if (hasSection('toc')) pageNumber++
      
      // Add pages for each section before this one
      pageNumber += index
      
      return pageNumber
    }

    const getTemplateStyleLabel = (style) => {
      const labels = {
        'professional': 'Professional',
        'executive': 'Executive',
        'modern': 'Modern',
        'classic': 'Classic'
      }
      return labels[style] || 'Professional'
    }

    const formatDate = (date) => {
      return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      })
    }

    return {
      visibleSections,
      hasSection,
      getSectionConfig,
      getEstimatedPageNumber,
      getTemplateStyleLabel,
      formatDate
    }
  }
}
</script>

<style scoped>
.report-preview-renderer {
  background: white;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

.preview-page {
  min-height: 11in;
  width: 100%;
  padding: 1in;
  border-bottom: 2px solid #e9ecef;
  page-break-after: always;
  position: relative;
}

.preview-page:last-child {
  border-bottom: none;
}

.page-break-before {
  page-break-before: always;
}

.page-content {
  height: 100%;
  display: flex;
  flex-direction: column;
}

/* Cover Page Styles */
.cover-page {
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
}

.company-logo {
  margin-bottom: 2rem;
}

.logo-img {
  max-height: 100px;
  max-width: 200px;
  object-fit: contain;
}

.report-title {
  color: #2c3e50;
  font-weight: 300;
  font-size: 3rem;
  line-height: 1.2;
  margin-bottom: 2rem;
}

.client-name {
  color: #34495e;
  font-weight: 400;
  margin-bottom: 0.5rem;
}

.client-subtitle {
  font-size: 1.2rem;
  font-style: italic;
}

.report-date {
  font-size: 1.1rem;
  margin-top: 2rem;
}

.template-badge {
  margin-top: 3rem;
}

/* Table of Contents Styles */
.toc-page .page-title {
  color: #2c3e50;
  border-bottom: 3px solid #3498db;
  padding-bottom: 0.5rem;
  margin-bottom: 2rem;
}

.toc-list {
  max-width: 600px;
}

.toc-item {
  padding: 1rem 0;
  border-bottom: 1px dotted #bdc3c7;
  font-size: 1.1rem;
}

.toc-item:last-child {
  border-bottom: none;
}

.section-number {
  font-weight: bold;
  color: #3498db;
  min-width: 30px;
  text-align: center;
}

.section-title {
  flex-grow: 1;
  color: #2c3e50;
}

.page-number {
  font-weight: bold;
  color: #7f8c8d;
  min-width: 40px;
  text-align: right;
}

/* Content Page Styles */
.content-page {
  background: white;
}

.page-header {
  border-bottom: 2px solid #ecf0f1;
  padding-bottom: 1rem;
}

.page-title {
  color: #2c3e50;
  font-size: 2rem;
  font-weight: 400;
  margin-bottom: 0.5rem;
}

.page-subtitle {
  font-size: 1.1rem;
  font-style: italic;
}

.section-content {
  flex-grow: 1;
  margin-top: 1rem;
}

/* Footer Page Styles */
.footer-page {
  display: flex;
  align-items: center;
  justify-content: center;
  background: #f8f9fa;
}

.report-footer {
  max-width: 600px;
  margin: 0 auto;
}

.disclaimer {
  padding: 2rem;
  background: white;
  border-radius: 0.5rem;
  border: 1px solid #dee2e6;
}

.disclaimer h6 {
  color: #e74c3c;
  margin-bottom: 1rem;
}

.disclaimer p {
  line-height: 1.6;
  color: #6c757d;
}

.contact-info {
  margin-top: 2rem;
  padding-top: 1rem;
  border-top: 1px solid #dee2e6;
}

/* Print Styles */
@media print {
  .preview-page {
    page-break-after: always;
    margin: 0;
    padding: 0.5in;
  }
  
  .page-break-before {
    page-break-before: always;
  }
}

/* Responsive Design */
@media (max-width: 768px) {
  .preview-page {
    padding: 0.5in;
  }
  
  .report-title {
    font-size: 2rem;
  }
  
  .toc-item {
    font-size: 1rem;
  }
  
  .page-title {
    font-size: 1.5rem;
  }
}
</style>