version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Pre-build started on `date`
      - echo Setting up Docker buildx for multi-platform builds...
      - docker buildx create --use --name multiarch --driver docker-container || true
      - docker buildx inspect --bootstrap
  build:
    commands:
      - echo Build started on `date`
      - echo Building Vue.js Docker image for linux/amd64...
      - |
        if [ "$IMAGE_TAG" = "staging" ]; then
          API_URL="http://staging.retirementadvisorpro.com"
          FRONTEND_URL="http://staging.retirementadvisorpro.com"
        else
          API_URL="http://app.retirementadvisorpro.com"
          FRONTEND_URL="http://app.retirementadvisorpro.com"
        fi
      - echo "Using production Dockerfile with nginx for better stability"
      - echo "API_URL: $API_URL"
      - echo "FRONTEND_URL: $FRONTEND_URL"
      - docker buildx build --platform linux/amd64 -f docker/Dockerfile.frontend.prod -t $IMAGE_REPO_NAME:$IMAGE_TAG --build-arg VITE_API_BASE_URL=$API_URL --build-arg VITE_FRONTEND_URL=$FRONTEND_URL --load .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"frontend","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  name: frontend-build-$(date +%Y-%m-%d)