# Generated by Django 5.2.5 on 2025-09-01 01:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_broadcastmessage_broadcastdelivery_and_more'),
        ('report_center', '0002_add_ai_usage_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkExportJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('export_config', models.JSONField(help_text='Export configuration including format, options, filters')),
                ('client_ids', models.JSONField(default=list, help_text='List of client IDs to export')),
                ('scenario_ids', models.JSONField(default=list, help_text='List of scenario IDs to export')),
                ('template_ids', models.JSONField(default=list, help_text='List of template IDs to use')),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('successful_exports', models.PositiveIntegerField(blank=True, null=True)),
                ('failed_exports', models.PositiveIntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to the generated export file (ZIP for multiple files)', max_length=500, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, help_text='Detailed error information for failed individual exports', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bulk Export Job',
                'verbose_name_plural': 'Bulk Export Jobs',
                'db_table': 'bulk_export_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled'), ('completed', 'Completed')], default='active', max_length=50)),
                ('client_filter', models.JSONField(blank=True, help_text='Client filtering criteria for bulk scheduling', null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=50)),
                ('frequency_config', models.JSONField(default=dict, help_text='Detailed frequency configuration (day of week, day of month, etc.)')),
                ('scheduled_time', models.TimeField(help_text='Time of day to generate the report')),
                ('timezone', models.CharField(default='UTC', help_text='Timezone for scheduling', max_length=100)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('both', 'PDF + PowerPoint')], default='pdf', max_length=50)),
                ('generation_options', models.JSONField(default=dict, help_text='Report generation options (page size, orientation, etc.)')),
                ('auto_email', models.BooleanField(default=False, help_text='Automatically email the report when generated')),
                ('email_recipients', models.JSONField(default=list, help_text='List of email addresses to send the report to')),
                ('email_subject_template', models.CharField(blank=True, help_text='Email subject template with variables', max_length=255)),
                ('email_body_template', models.TextField(blank=True, help_text='Email body template with variables')),
                ('next_run', models.DateTimeField(blank=True, help_text='Next scheduled execution time', null=True)),
                ('last_run', models.DateTimeField(blank=True, help_text='Last execution time', null=True)),
                ('run_count', models.PositiveIntegerField(default=0, help_text='Number of times this schedule has run')),
                ('success_count', models.PositiveIntegerField(default=0, help_text='Number of successful executions')),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Number of failed executions')),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional end date for the schedule', null=True)),
                ('max_runs', models.PositiveIntegerField(blank=True, help_text='Maximum number of runs (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'db_table': 'report_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportScheduleExecution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=50)),
                ('scheduled_for', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_reports', models.JSONField(default=list, help_text='List of generated report IDs or file paths')),
                ('emails_sent', models.PositiveIntegerField(default=0, help_text='Number of emails sent for this execution')),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, help_text='Detailed error information', null=True)),
                ('execution_time_seconds', models.FloatField(blank=True, help_text='Total execution time in seconds', null=True)),
                ('reports_generated', models.PositiveIntegerField(default=0, help_text='Number of reports generated in this execution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Schedule Execution',
                'verbose_name_plural': 'Report Schedule Executions',
                'db_table': 'report_schedule_executions',
                'ordering': ['-scheduled_for'],
            },
        ),
        migrations.RenameIndex(
            model_name='aiusagetracking',
            new_name='report_ai_u_feature_c2fc01_idx',
            old_name='report_ai_u_feature_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagetracking',
            new_name='report_ai_u_user_id_b84a52_idx',
            old_name='report_ai_u_user_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagetracking',
            new_name='report_ai_u_timesta_65c907_idx',
            old_name='report_ai_u_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagetracking',
            new_name='report_ai_u_cost_a7b081_idx',
            old_name='report_ai_u_cost_idx',
        ),
        migrations.AddField(
            model_name='bulkexportjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_export_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Specific client for the report (if not bulk)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='core.client'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='scenario',
            field=models.ForeignKey(blank=True, help_text='Specific scenario for the report', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='core.scenario'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='report_center.reporttemplate'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportscheduleexecution',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='report_center.reportschedule'),
        ),
        migrations.AddIndex(
            model_name='bulkexportjob',
            index=models.Index(fields=['user'], name='bulk_export_user_id_bcd0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkexportjob',
            index=models.Index(fields=['status'], name='bulk_export_status_c97441_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkexportjob',
            index=models.Index(fields=['created_at'], name='bulk_export_created_9529f7_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkexportjob',
            index=models.Index(fields=['completed_at'], name='bulk_export_complet_0280ba_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['user'], name='report_sche_user_id_5728c3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['status'], name='report_sche_status_bb62b9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['next_run'], name='report_sche_next_ru_270fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['frequency'], name='report_sche_frequen_825450_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['template'], name='report_sche_templat_75e449_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['client'], name='report_sche_client__fd0ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['created_at'], name='report_sche_created_614495_idx'),
        ),
        migrations.AddIndex(
            model_name='reportscheduleexecution',
            index=models.Index(fields=['schedule'], name='report_sche_schedul_db3264_idx'),
        ),
        migrations.AddIndex(
            model_name='reportscheduleexecution',
            index=models.Index(fields=['status'], name='report_sche_status_4fe5a8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportscheduleexecution',
            index=models.Index(fields=['scheduled_for'], name='report_sche_schedul_2562e8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportscheduleexecution',
            index=models.Index(fields=['created_at'], name='report_sche_created_8b934b_idx'),
        ),
    ]
