name: 🧩 Module Task
description: Track a specific module or component build task.
title: "[Module] "
labels: ["feature", "module"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🧱 Module Task
        Please fill in the following details to create a new module or feature.

  - type: input
    id: module_name
    attributes:
      label: Module Name
      description: What part of the application is this for?
      placeholder: e.g. ScenarioCreate.vue or IncomeCalculator
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What is the purpose of this module? What should it do?
      placeholder: Describe the problem it's solving and the outcome.
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks / Checklist
      description: Break down what needs to be done.
      placeholder: |
        - [ ] Build UI
        - [ ] Connect to API
        - [ ] Write tests
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
      default: 1