FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY backend/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY backend/ .
EXPOSE 8000
CMD ["gunicorn", "retirementadvisorpro.wsgi:application", "--bind", "0.0.0.0:8000"]