--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Debian 14.18-1.pgdg120+1)
-- Dumped by pg_dump version 14.18 (Debian 14.18-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: core_client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_client (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    birthdate date NOT NULL,
    gender character varying(10) NOT NULL,
    tax_status character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    notes text,
    is_deleted boolean NOT NULL,
    status character varying(20) NOT NULL,
    advisor_id bigint NOT NULL
);


ALTER TABLE public.core_client OWNER TO postgres;

--
-- Name: core_client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    phone_number character varying(20) NOT NULL,
    company_name character varying(255) NOT NULL,
    website_url character varying(200) NOT NULL,
    address character varying(255) NOT NULL,
    city character varying(100) NOT NULL,
    state character varying(100) NOT NULL,
    zip_code character varying(20) NOT NULL,
    white_label_company_name character varying(100) NOT NULL,
    white_label_support_email character varying(254) NOT NULL,
    primary_color character varying(20) NOT NULL,
    logo character varying(100)
);


ALTER TABLE public.core_customuser OWNER TO postgres;

--
-- Name: core_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.core_customuser_groups OWNER TO postgres;

--
-- Name: core_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.core_customuser_user_permissions OWNER TO postgres;

--
-- Name: core_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_incomesource; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_incomesource (
    id bigint NOT NULL,
    owned_by character varying(10) NOT NULL,
    income_type character varying(200) NOT NULL,
    income_name character varying(50) NOT NULL,
    current_asset_balance numeric(12,2),
    monthly_amount numeric(10,2),
    age_to_begin_withdrawal integer,
    age_to_end_withdrawal integer NOT NULL,
    rate_of_return double precision NOT NULL,
    cola double precision NOT NULL,
    exclusion_ratio double precision NOT NULL,
    tax_rate double precision NOT NULL,
    scenario_id bigint NOT NULL,
    monthly_contribution numeric(10,2),
    CONSTRAINT core_incomesource_age_to_begin_withdrawal_check CHECK ((age_to_begin_withdrawal >= 0)),
    CONSTRAINT core_incomesource_age_to_end_withdrawal_check CHECK ((age_to_end_withdrawal >= 0))
);


ALTER TABLE public.core_incomesource OWNER TO postgres;

--
-- Name: core_incomesource_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_incomesource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_incomesource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_scenario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_scenario (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    description text NOT NULL,
    medicare_age integer NOT NULL,
    mortality_age integer NOT NULL,
    retirement_age integer NOT NULL,
    retirement_year integer NOT NULL,
    share_with_client boolean NOT NULL,
    spouse_medicare_age integer,
    spouse_mortality_age integer,
    spouse_retirement_age integer,
    part_b_inflation_rate double precision NOT NULL,
    part_d_inflation_rate double precision NOT NULL,
    "FRA_amount" numeric(10,2),
    roth_conversion_annual_amount numeric(12,2),
    roth_conversion_duration integer,
    roth_conversion_start_year integer,
    CONSTRAINT core_scenario_medicare_age_check CHECK ((medicare_age >= 0)),
    CONSTRAINT core_scenario_mortality_age_check CHECK ((mortality_age >= 0)),
    CONSTRAINT core_scenario_retirement_age_check CHECK ((retirement_age >= 0)),
    CONSTRAINT core_scenario_retirement_year_check CHECK ((retirement_year >= 0)),
    CONSTRAINT core_scenario_roth_conversion_duration_check CHECK ((roth_conversion_duration >= 0)),
    CONSTRAINT core_scenario_roth_conversion_start_year_check CHECK ((roth_conversion_start_year >= 0)),
    CONSTRAINT core_scenario_spouse_medicare_age_check CHECK ((spouse_medicare_age >= 0)),
    CONSTRAINT core_scenario_spouse_mortality_age_check CHECK ((spouse_mortality_age >= 0)),
    CONSTRAINT core_scenario_spouse_retirement_age_check CHECK ((spouse_retirement_age >= 0))
);


ALTER TABLE public.core_scenario OWNER TO postgres;

--
-- Name: core_scenario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_scenario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_scenario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_spouse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_spouse (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    birthdate date NOT NULL,
    gender character varying(10) NOT NULL,
    client_id bigint NOT NULL
);


ALTER TABLE public.core_spouse OWNER TO postgres;

--
-- Name: core_spouse_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_spouse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_spouse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_yearlycalculation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.core_yearlycalculation (
    id bigint NOT NULL,
    year integer NOT NULL,
    age integer NOT NULL,
    spouse_age integer,
    total_income numeric(12,2) NOT NULL,
    taxable_income numeric(12,2) NOT NULL,
    federal_tax numeric(12,2) NOT NULL,
    medicare_base numeric(12,2) NOT NULL,
    irmaa_surcharge numeric(12,2) NOT NULL,
    net_income numeric(12,2) NOT NULL,
    scenario_id bigint NOT NULL,
    CONSTRAINT core_yearlycalculation_age_check CHECK ((age >= 0)),
    CONSTRAINT core_yearlycalculation_spouse_age_check CHECK ((spouse_age >= 0)),
    CONSTRAINT core_yearlycalculation_year_check CHECK ((year >= 0))
);


ALTER TABLE public.core_yearlycalculation OWNER TO postgres;

--
-- Name: core_yearlycalculation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.core_yearlycalculation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_yearlycalculation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO postgres;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO postgres;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: core_client core_client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_client
    ADD CONSTRAINT core_client_pkey PRIMARY KEY (id);


--
-- Name: core_customuser core_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser
    ADD CONSTRAINT core_customuser_email_key UNIQUE (email);


--
-- Name: core_customuser_groups core_customuser_groups_customuser_id_group_id_7990e9c6_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser_groups
    ADD CONSTRAINT core_customuser_groups_customuser_id_group_id_7990e9c6_uniq UNIQUE (customuser_id, group_id);


--
-- Name: core_customuser_groups core_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser_groups
    ADD CONSTRAINT core_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: core_customuser core_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser
    ADD CONSTRAINT core_customuser_pkey PRIMARY KEY (id);


--
-- Name: core_customuser_user_permissions core_customuser_user_per_customuser_id_permission_49ea742a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser_user_permissions
    ADD CONSTRAINT core_customuser_user_per_customuser_id_permission_49ea742a_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: core_customuser_user_permissions core_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser_user_permissions
    ADD CONSTRAINT core_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: core_customuser core_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser
    ADD CONSTRAINT core_customuser_username_key UNIQUE (username);


--
-- Name: core_incomesource core_incomesource_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_incomesource
    ADD CONSTRAINT core_incomesource_pkey PRIMARY KEY (id);


--
-- Name: core_scenario core_scenario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_scenario
    ADD CONSTRAINT core_scenario_pkey PRIMARY KEY (id);


--
-- Name: core_spouse core_spouse_client_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_spouse
    ADD CONSTRAINT core_spouse_client_id_key UNIQUE (client_id);


--
-- Name: core_spouse core_spouse_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_spouse
    ADD CONSTRAINT core_spouse_pkey PRIMARY KEY (id);


--
-- Name: core_yearlycalculation core_yearlycalculation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_yearlycalculation
    ADD CONSTRAINT core_yearlycalculation_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: core_client_advisor_id_7c33caf4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_client_advisor_id_7c33caf4 ON public.core_client USING btree (advisor_id);


--
-- Name: core_customuser_email_e02ad5f6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_customuser_email_e02ad5f6_like ON public.core_customuser USING btree (email varchar_pattern_ops);


--
-- Name: core_customuser_groups_customuser_id_976bc4d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_customuser_groups_customuser_id_976bc4d7 ON public.core_customuser_groups USING btree (customuser_id);


--
-- Name: core_customuser_groups_group_id_301aeff4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_customuser_groups_group_id_301aeff4 ON public.core_customuser_groups USING btree (group_id);


--
-- Name: core_customuser_user_permissions_customuser_id_ebd2ce6c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_customuser_user_permissions_customuser_id_ebd2ce6c ON public.core_customuser_user_permissions USING btree (customuser_id);


--
-- Name: core_customuser_user_permissions_permission_id_80ceaab9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_customuser_user_permissions_permission_id_80ceaab9 ON public.core_customuser_user_permissions USING btree (permission_id);


--
-- Name: core_customuser_username_0e60666f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_customuser_username_0e60666f_like ON public.core_customuser USING btree (username varchar_pattern_ops);


--
-- Name: core_incomesource_scenario_id_b3217073; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_incomesource_scenario_id_b3217073 ON public.core_incomesource USING btree (scenario_id);


--
-- Name: core_scenario_client_id_3891f40a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_scenario_client_id_3891f40a ON public.core_scenario USING btree (client_id);


--
-- Name: core_yearlycalculation_scenario_id_001d42b6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX core_yearlycalculation_scenario_id_001d42b6 ON public.core_yearlycalculation USING btree (scenario_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_core_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_core_customuser_id FOREIGN KEY (user_id) REFERENCES public.core_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_client core_client_advisor_id_7c33caf4_fk_core_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_client
    ADD CONSTRAINT core_client_advisor_id_7c33caf4_fk_core_customuser_id FOREIGN KEY (advisor_id) REFERENCES public.core_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_customuser_groups core_customuser_grou_customuser_id_976bc4d7_fk_core_cust; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser_groups
    ADD CONSTRAINT core_customuser_grou_customuser_id_976bc4d7_fk_core_cust FOREIGN KEY (customuser_id) REFERENCES public.core_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_customuser_groups core_customuser_groups_group_id_301aeff4_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser_groups
    ADD CONSTRAINT core_customuser_groups_group_id_301aeff4_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_customuser_user_permissions core_customuser_user_customuser_id_ebd2ce6c_fk_core_cust; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser_user_permissions
    ADD CONSTRAINT core_customuser_user_customuser_id_ebd2ce6c_fk_core_cust FOREIGN KEY (customuser_id) REFERENCES public.core_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_customuser_user_permissions core_customuser_user_permission_id_80ceaab9_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_customuser_user_permissions
    ADD CONSTRAINT core_customuser_user_permission_id_80ceaab9_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_incomesource core_incomesource_scenario_id_b3217073_fk_core_scenario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_incomesource
    ADD CONSTRAINT core_incomesource_scenario_id_b3217073_fk_core_scenario_id FOREIGN KEY (scenario_id) REFERENCES public.core_scenario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_scenario core_scenario_client_id_3891f40a_fk_core_client_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_scenario
    ADD CONSTRAINT core_scenario_client_id_3891f40a_fk_core_client_id FOREIGN KEY (client_id) REFERENCES public.core_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_spouse core_spouse_client_id_67f62c64_fk_core_client_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_spouse
    ADD CONSTRAINT core_spouse_client_id_67f62c64_fk_core_client_id FOREIGN KEY (client_id) REFERENCES public.core_client(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_yearlycalculation core_yearlycalculation_scenario_id_001d42b6_fk_core_scenario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.core_yearlycalculation
    ADD CONSTRAINT core_yearlycalculation_scenario_id_001d42b6_fk_core_scenario_id FOREIGN KEY (scenario_id) REFERENCES public.core_scenario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_core_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_core_customuser_id FOREIGN KEY (user_id) REFERENCES public.core_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_core_cust; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_core_cust FOREIGN KEY (user_id) REFERENCES public.core_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

