# Generated by Django 5.2.1 on 2025-06-03 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='medicare_age',
            field=models.PositiveIntegerField(default=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='mortality_age',
            field=models.PositiveIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='retirement_age',
            field=models.PositiveIntegerField(default=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='retirement_year',
            field=models.PositiveIntegerField(default=2030),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='share_with_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scenario',
            name='spouse_medicare_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='spouse_mortality_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='spouse_retirement_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned_by', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse')], max_length=10)),
                ('income_type', models.CharField(max_length=200)),
                ('income_name', models.CharField(max_length=50)),
                ('balance_at_retirement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('age_to_begin_withdrawal', models.PositiveIntegerField(blank=True, null=True)),
                ('age_to_end_withdrawal', models.PositiveIntegerField()),
                ('rate_of_return', models.FloatField(default=0)),
                ('cola', models.FloatField(default=0)),
                ('exclusion_ratio', models.FloatField(default=0)),
                ('tax_rate', models.FloatField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to='core.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('spouse_age', models.PositiveIntegerField(blank=True, null=True)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('federal_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medicare_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('irmaa_surcharge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_calculations', to='core.scenario')),
            ],
        ),
    ]
