# Generated by Django 5.2.2 on 2025-06-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scenario_description_scenario_medicare_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesource',
            name='owned_by',
            field=models.CharField(choices=[('primary', 'Primary'), ('spouse', 'Spouse')], max_length=10),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='medicare_age',
            field=models.PositiveIntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='mortality_age',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='retirement_age',
            field=models.PositiveIntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='retirement_year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='spouse_medicare_age',
            field=models.PositiveIntegerField(blank=True, default=65, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='spouse_mortality_age',
            field=models.PositiveIntegerField(blank=True, default=90, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='spouse_retirement_age',
            field=models.PositiveIntegerField(blank=True, default=65, null=True),
        ),
    ]
