# Generated by Django 5.2.2 on 2025-06-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_incomesource_owned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='monthly_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
