# Generated by Django 5.2.2 on 2025-06-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_incomesource_monthly_contribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomesource',
            old_name='balance_at_retirement',
            new_name='current_asset_balance',
        ),
    ]
