# Generated by Django 5.2.1 on 2025-06-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_balance_at_retirement_incomesource_current_asset_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='part_b_inflation_rate',
            field=models.FloatField(default=6.0),
        ),
        migrations.AddField(
            model_name='scenario',
            name='part_d_inflation_rate',
            field=models.FloatField(default=6.0),
        ),
    ]
