# Generated by Django 5.2.1 on 2025-06-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scenario_part_b_inflation_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='FRA_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
