# Generated by Django 5.2.1 on 2025-06-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_scenario_fra_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='roth_conversion_annual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='roth_conversion_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='roth_conversion_start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
