# Generated by Django 5.2.1 on 2025-06-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='apply_standard_deduction',
            field=models.BooleanField(default=True, help_text='Apply IRS standard deduction in tax calculations.'),
        ),
    ]
