# Generated by Django 5.2.1 on 2025-07-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reporttemplate_templateslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='max_to_convert',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount to convert to Roth', max_digits=12, null=True),
        ),
    ]
