# Generated by Django 5.2.1 on 2025-07-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_incomesource_max_to_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='income_vs_cost_percent',
            field=models.IntegerField(default=0, help_text='Percentage of federal tax + medicare to gross income'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='medicare_irmaa_percent',
            field=models.IntegerField(default=0, help_text='Percentage of IRMAA surcharges to total medicare costs'),
        ),
    ]
