# Generated by Django 5.2.5 on 2025-08-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comparisonpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='primary_state',
            field=models.CharField(blank=True, default='', help_text='Primary tax state for this scenario', max_length=50),
        ),
    ]
