# Generated by Django 5.2.5 on 2025-08-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_primary_state_to_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='age_established',
            field=models.PositiveIntegerField(blank=True, help_text='Age when the asset was established', null=True),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='age_last_contribution',
            field=models.PositiveIntegerField(blank=True, help_text='Age when contributions will end', null=True),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='employer_match',
            field=models.FloatField(default=0, help_text='Employer contribution match percentage'),
        ),
        migrations.AddField(
            model_name='incomesource',
            name='is_contributing',
            field=models.BooleanField(default=False, help_text='Currently contributing to this investment'),
        ),
    ]
