# Generated by Django 5.2.5 on 2025-08-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_investment_fields_to_incomesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='primary_ss_claiming_age',
            field=models.FloatField(blank=True, help_text="Primary client's Social Security claiming age", null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='spouse_ss_claiming_age',
            field=models.FloatField(blank=True, help_text="Spouse's Social Security claiming age", null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='ss_include_irmaa',
            field=models.BooleanField(default=False, help_text='Include IRMAA impact in Social Security analysis'),
        ),
    ]
