# Generated by Django 5.2.5 on 2025-08-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_scenario_primary_ss_claiming_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_disclosure',
            field=models.TextField(blank=True, help_text='Custom disclosure text to appear on scenario reports'),
        ),
    ]
