# Generated by Django 5.2.5 on 2025-08-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_custom_disclosure'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='reduction_2030_ss',
            field=models.BooleanField(default=False, help_text='Apply Social Security benefit reduction'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='ss_adjustment_amount',
            field=models.FloatField(default=23.0, help_text='Amount of SS adjustment'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='ss_adjustment_direction',
            field=models.CharField(default='decrease', help_text='Direction of SS adjustment', max_length=20),
        ),
        migrations.AddField(
            model_name='scenario',
            name='ss_adjustment_type',
            field=models.CharField(default='percentage', help_text='Type of SS adjustment', max_length=20),
        ),
        migrations.AddField(
            model_name='scenario',
            name='ss_adjustment_year',
            field=models.PositiveIntegerField(default=2030, help_text='Year to start Social Security adjustment'),
        ),
    ]
