# Generated by Django 5.2.5 on 2025-08-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_ss_adjustment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='custom_annual_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom annual deduction amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='federal_standard_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Federal standard deduction amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='is_dependent',
            field=models.BooleanField(default=False, help_text='Filed as dependent (affects deduction limits)'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='primary_blind',
            field=models.BooleanField(default=False, help_text='Primary client is blind (additional deduction)'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='spouse_blind',
            field=models.BooleanField(default=False, help_text='Spouse is blind (additional deduction)'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='state_standard_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='State standard deduction amount', max_digits=10, null=True),
        ),
    ]
