# Generated by Django 5.2.5 on 2025-08-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_emailaccount_lead_communication_activitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='ai_analysis_date',
            field=models.DateTimeField(blank=True, help_text='When AI analysis was performed', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='ai_model_version',
            field=models.CharField(blank=True, help_text='Version of AI model used for analysis', max_length=50),
        ),
        migrations.AddField(
            model_name='communication',
            name='ai_priority_score',
            field=models.FloatField(blank=True, help_text='Overall priority score combining sentiment, urgency, and client value', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='ai_response_confidence',
            field=models.FloatField(blank=True, help_text='Confidence level of AI response suggestion (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='ai_sentiment_label',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], max_length=20),
        ),
        migrations.AddField(
            model_name='communication',
            name='ai_sentiment_score',
            field=models.FloatField(blank=True, help_text='AI sentiment analysis score (-1.0 to 1.0, negative=negative, positive=positive)', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='ai_suggested_response',
            field=models.TextField(blank=True, help_text='AI-generated suggested response'),
        ),
        migrations.AddField(
            model_name='communication',
            name='ai_topics',
            field=models.JSONField(default=list, help_text='AI-detected topics/categories in the communication'),
        ),
        migrations.AddField(
            model_name='communication',
            name='ai_urgency_score',
            field=models.FloatField(blank=True, help_text='AI urgency detection score (0.0 to 1.0)', null=True),
        ),
    ]
