# Generated by Django 5.2.5 on 2025-08-27 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_documentcategory_document_documentpermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='portal_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='portal_invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='portal_invitation_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='portal_last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='portal_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_portal_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
