# Generated by Django 5.2.5 on 2025-08-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_client_portal_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Custom permissions dictionary for granular access control'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('support', 'Support Staff'), ('analyst', 'Business Analyst'), ('billing', 'Billing Administrator')], help_text='Specific admin role defining access level', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user has admin access to platform management'),
        ),
    ]
