# Generated by Django 5.2.5 on 2025-08-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_admin_audit_logging'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='admin_audit_admin_u_f6191e_idx',
            old_name='admin_audit_admin_user_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='admin_audit_target__3b0625_idx',
            old_name='admin_audit_target_user_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='admin_audit_action__9b5065_idx',
            old_name='admin_audit_action_type_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='admin_audit_ip_addr_194dcc_idx',
            old_name='admin_audit_ip_address_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='admin_audit_risk_le_11442d_idx',
            old_name='admin_audit_risk_level_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='admin_audit_timesta_38861a_idx',
            old_name='admin_audit_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='userimpersonationlog',
            new_name='user_impers_admin_u_6619a7_idx',
            old_name='impersonation_admin_user_idx',
        ),
        migrations.RenameIndex(
            model_name='userimpersonationlog',
            new_name='user_impers_target__d82439_idx',
            old_name='impersonation_target_user_idx',
        ),
        migrations.RenameIndex(
            model_name='userimpersonationlog',
            new_name='user_impers_is_acti_472e40_idx',
            old_name='impersonation_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='userimpersonationlog',
            new_name='user_impers_flagged_6a9b67_idx',
            old_name='impersonation_flagged_idx',
        ),
        migrations.RenameIndex(
            model_name='userimpersonationlog',
            new_name='user_impers_session_ebe05b_idx',
            old_name='impersonation_session_key_idx',
        ),
        migrations.RenameIndex(
            model_name='userimpersonationlog',
            new_name='user_impers_start_t_28cc3f_idx',
            old_name='impersonation_timestamp_idx',
        ),
    ]
