# Generated by Django 5.2.5 on 2025-09-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_broadcastmessage_broadcastdelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sms_consent',
            field=models.BooleanField(default=False, help_text='User consent to receive SMS messages for company information and updates'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_consent_date',
            field=models.DateTimeField(blank=True, help_text='Date when SMS consent was given', null=True),
        ),
    ]
