# Generated by Django 5.2.6 on 2025-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_customuser_sms_consent_customuser_sms_consent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(choices=[('password', 'Email/Password'), ('google-oauth2', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple'), ('linkedin', 'LinkedIn'), ('microsoft', 'Microsoft')], default='password', help_text='Authentication provider used for login', max_length=50),
        ),
    ]
