# Generated by Django 5.2.6 on 2025-09-07 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_auth_provider_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together={('advisor', 'name', 'category_type')},
        ),
    ]
