# Generated by Django 5.2.6 on 2025-09-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_affiliate_affiliateclick_affiliateconversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='portal_password',
            field=models.CharField(blank=True, help_text='Hashed password for affiliate portal access', max_length=255),
        ),
    ]
