# Generated by Django 5.2.6 on 2025-09-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_affiliate_portal_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for user tracking (e.g., affiliate attribution)'),
        ),
    ]
