# Generated by Django 5.2.6 on 2025-09-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_user_metadata_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='stripe_account_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('restricted', 'Restricted'), ('disabled', 'Disabled')], help_text='Current status of Stripe Connect account', max_length=50),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID for automated payouts', max_length=255),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False, help_text='Whether Stripe payouts are enabled for this account'),
        ),
        migrations.AddField(
            model_name='affiliatepayout',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, help_text='Stripe Connect transfer ID', max_length=255),
        ),
    ]
